# Generated by Django 3.2.4 on 2021-07-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-pk']},
        ),
    ]
